DATA_SAVE_PATH: data

MAP: Town04_Opt

HERO_VEHICLE: vehicle.tesla.model3

SAVE_INTERVAL: 5

SAVE_LIDAR_LABELS: False

SENSOR_GROUP_LIST:
    - NAME: lidar
      TYPE: lidar_group
      SEMANTIC: True
      SENSOR_GROUP: 
          - TYPE: lidar.ray_cast_semantic
            SETUP: {
                range: '150', 
                points_per_second: '1228800',
                rotation_frequency: '20', 
                lower_fov: '-90',
                channels: '128',
            }
            TRANSFORM: {
                x: 25,
                y: 25,
                z: 3,
            }

          - TYPE: lidar.ray_cast_semantic
            SETUP: {
                range: '150', 
                points_per_second: '1228800',
                rotation_frequency: '20', 
                lower_fov: '-90',
                channels: '128',
            }
            TRANSFORM: {
                x: -25,
                y: 25,
                z: 3,
            }
    
          - TYPE: lidar.ray_cast_semantic
            SETUP: {
                range: '150', 
                points_per_second: '1228800',
                rotation_frequency: '20', 
                lower_fov: '-90',
                channels: '128',
            }
            TRANSFORM: {
                x: 25,
                y: -25,
                z: 3,
            }

          - TYPE: lidar.ray_cast_semantic
            SETUP: {
                range: '150', 
                points_per_second: '1228800',
                rotation_frequency: '20', 
                lower_fov: '-90',
                channels: '128',
            }
            TRANSFORM: {
                x: -25,
                y: -25,
                z: 3,
            }
          - TYPE: lidar.ray_cast_semantic
            SETUP: {
                range: '150', 
                points_per_second: '1228800',
                rotation_frequency: '20', 
                lower_fov: '-90',
                channels: '128',
            }
            TRANSFORM: {
                x: 0,
                y: 0,
                z: 3,
            }

    - NAME: camera1
      TYPE: camera_rgb
      SENSOR_GROUP: 
          - TYPE: camera.rgb
            SETUP: {
                image_size_x: '1920',
                image_size_y: '1080',
                lens_circle_multiplier: '3.0',
                lens_circle_falloff: '3.0',
                chromatic_aberration_intensity: '0.5',
                chromatic_aberration_offset: '0',
                fov: '160',
            }
            TRANSFORM: {
                x: 0,
                y: 0,
                z: 1.8,
            }