DATA_SAVE_PATH: data

MAP: Town04_Opt

HERO_VEHICLE: vehicle.tesla.model3

NUM_OF_ENV_VEHICLES: 300

TOTAL_TIMESTAMPS: 2000

LIDAR_GROUP_LIST:
    - NAME: one_lidar_on_head_16
      LIDARS: 
          - NAME: head_center_lidar
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 0.4,
                y: 0.0,
                z: 1.35,
                yaw: 0.0
            }
            REFERENCE_LIDAR: True
