DATA_SAVE_PATH: data

MAP: Town04_Opt

HERO_VEHICLE: vehicle.tesla.model3

NUM_OF_ENV_VEHICLES: 0

TOTAL_TIMESTAMPS: 10

SAVE_INTERVAL: 10

SENSOR_GROUP_LIST:
    - NAME: point16
      TYPE: lidar_group
      SENSOR_GROUP: 
          - TYPE: lidar.ray_cast
            SETUP: {
                range: '120', 
                points_per_second: '7300000',
                rotation_frequency: '20', 
                channels: '64',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '360.0'
            }
            TRANSFORM: {
                x: 0.4,
                y: 0.0,
                z: 2,
                yaw: 0.0
            }