DATA_SAVE_PATH: data

MAP: Town04_Opt

HERO_VEHICLE: vehicle.tesla.model3

NUM_OF_ENV_VEHICLES: 200

TOTAL_TIMESTAMPS: 2000

SAVE_INTERVAL: 10

SENSOR_GROUP_LIST:
    - NAME: one_lidar_on_head_16
      TYPE: lidar_group
      REFERENCE_LIDAR: 0
      SEMANTIC: False
      SENSOR_GROUP: 
          - NAME: head_center_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 0.4,
                y: 0.0,
                z: 1.35,
                yaw: 0.0
            }
    
    - NAME: two_lidars_on_light_06
      TYPE: lidar_group
      REFERENCE_LIDAR: 0
      SEMANTIC: False
      SENSOR_GROUP:
          - NAME: light_left_side_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 2.0,
                y: 0.7,
                z: 0.7,
                yaw: 30.0
            }

          - NAME: light_right_side_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 2.0,
                y: -0.7,
                z: 0.7,
                yaw: -30.0
            }

    - NAME: three_lidars_on_bumper_04
      TYPE: lidar_group
      REFERENCE_LIDAR: 0
      SEMANTIC: False
      SENSOR_GROUP: 
          - NAME: bumper_left_side_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 2.3,
                y: 0.0,
                z: 0.6,
                yaw: 0.0
            }

          - NAME: bumper_right_side_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 1.0,
                y: -1.0,
                z: 0.6,
                yaw: -90.0
            }

          - NAME: bumper_center_lidar
            TYPE: lidar.ray_cast
            SETUP: {
                range: '150', 
                points_per_second: '576000',
                rotation_frequency: '20', 
                channels: '128',
                upper_fov: '12.5',
                lower_fov: '-12.5',
                horizontal_fov: '120.0'
            }
            TRANSFORM: {
                x: 1.0,
                y: 1.0,
                z: 0.6,
                yaw: 90.0
            }

